port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

turn:
  enabled: true
  domain: livekit.votre-domaine.fr
  tls_port: 5349
  udp_port: 3478
  external_tls: true

keys:
  cle_steevejobs_api: "Rentrer votre clé ici"