CREATE TABLE IF NOT EXISTS USER (
    id_user INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    mdp VARCHAR(255) NOT NULL,
    adresse VARCHAR(255),
    tel VARCHAR(255),
    role VARCHAR(50) NOT NULL,
    poste VARCHAR(255) NOT NULL,
    actif BOOLEAN DEFAULT TRUE,
    tentatives_echouees INT DEFAULT 0,
    bloque_jusqua TIMESTAMP NULL,
    date_dernier_echec TIMESTAMP NULL,
    taux INT DEFAULT 0,
    taux_patronal INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PRODUITS (
    id_produits INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prix_unitaire DECIMAL(10, 2),
    taux_tva DECIMAL(5, 2) DEFAULT 20.00,
    quantite INT,
    poids DECIMAL(10, 2),
    actif BOOLEAN DEFAULT TRUE,
    seuil_alerte INT
);

CREATE TABLE IF NOT EXISTS TIERS (
    id_tiers INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    tel VARCHAR(255) NOT NULL,
    siret VARCHAR(20),
    num_tva VARCHAR(50),
    actif BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS TICKETS (
    id_tickets INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sujet VARCHAR(255),
    description CLOB,
    service VARCHAR(255) NOT NULL,
    statut VARCHAR(50) NOT NULL DEFAULT 'EN_ATTENTE',
    non_lu_admin BOOLEAN NOT NULL DEFAULT FALSE,
    non_lu_auteur BOOLEAN NOT NULL DEFAULT FALSE,
    date_ouverture TIMESTAMP NOT NULL,
    id_auteur INT NOT NULL,
    CONSTRAINT fk_tickets_auteur FOREIGN KEY (id_auteur) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MESSAGES (
    id_messages INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenu CLOB NOT NULL,
    piece_jointe VARCHAR(255),
    date_envoi TIMESTAMP NOT NULL,
    id_auteur INT NOT NULL,
    id_ticket INT NOT NULL,
    CONSTRAINT fk_messages_auteur FOREIGN KEY (id_auteur) REFERENCES USER (id_user) ON DELETE CASCADE,
    CONSTRAINT fk_messages_ticket FOREIGN KEY (id_ticket) REFERENCES TICKETS (id_tickets) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PLANNING (
    id_planning INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jour_debut TIMESTAMP NOT NULL,
    jour_fin TIMESTAMP NOT NULL,
    type VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    couleur VARCHAR(20) DEFAULT '#7298E0',
    id_user INT NOT NULL,
    CONSTRAINT fk_planning_user FOREIGN KEY (id_user) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HEURES_TRAVAIL (
    id_heures INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INT NOT NULL,
    date_jour DATE NOT NULL,
    heure_debut_matin TIME,
    heure_fin_matin TIME,
    heure_debut_aprem TIME,
    heure_fin_aprem TIME,
    heures_total TIME,
    CONSTRAINT fk_heures_user FOREIGN KEY (id_user) REFERENCES USER (id_user) ON DELETE CASCADE,
    CONSTRAINT uq_heures_user_date UNIQUE (id_user, date_jour)
);

CREATE TABLE IF NOT EXISTS PERMISSION (
    id_permission INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_action VARCHAR(100) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ROLE_PERMISSION (
    nom_role VARCHAR(50) NOT NULL,
    id_permission INT NOT NULL,
    PRIMARY KEY (nom_role, id_permission),
    CONSTRAINT fk_role_perm FOREIGN KEY (id_permission) REFERENCES PERMISSION (id_permission) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DEMANDE_CONGE (
    id_demande_conge INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jour_debut TIMESTAMP NOT NULL,
    jour_fin TIMESTAMP NOT NULL,
    statut VARCHAR(50) NOT NULL DEFAULT 'EN_ATTENTE',
    commentaire_employe CLOB,
    commentaire_rh CLOB,
    date_demande TIMESTAMP NOT NULL,
    id_user INT NOT NULL,
    id_planning INT,
    CONSTRAINT fk_demande_user FOREIGN KEY (id_user) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FICHE_PAYE (
    id_paye INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    url VARCHAR(255) NOT NULL,
    id_user INT NOT NULL,
    CONSTRAINT fk_fiche_user FOREIGN KEY (id_user) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISIO (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(100) NOT NULL,
    createur_id INT NOT NULL,
    statut VARCHAR(50) DEFAULT 'PROGRAMMEE',
    type_reunion VARCHAR(50) NOT NULL DEFAULT 'PLANIFIEE',
    heure_programmee TIMESTAMP,
    heure_debut TIMESTAMP,
    heure_fin TIMESTAMP,
    CONSTRAINT fk_visio_createur FOREIGN KEY (createur_id) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISIO_INVITATIONS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visio_id INT NOT NULL,
    employe_id INT NOT NULL,
    CONSTRAINT fk_inv_visio FOREIGN KEY (visio_id) REFERENCES VISIO (id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_user FOREIGN KEY (employe_id) REFERENCES USER (id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DOCUMENTS (
    id_documents INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    total_ht DECIMAL(10, 2) NOT NULL,
    total_ttc DECIMAL(10, 2) NOT NULL,
    statut VARCHAR(50) NOT NULL,
    url VARCHAR(255) NOT NULL,
    id_tiers INT NOT NULL,
    id_vendeur INT,
    CONSTRAINT fk_doc_tiers FOREIGN KEY (id_tiers) REFERENCES TIERS (id_tiers) ON DELETE CASCADE,
    CONSTRAINT fk_doc_vendeur FOREIGN KEY (id_vendeur) REFERENCES USER (id_user) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS COMPOSER (
    id_documents INT NOT NULL,
    id_produits INT NOT NULL,
    quantite DECIMAL(10, 2) NOT NULL,
    prix_vente DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id_documents, id_produits),
    CONSTRAINT fk_composer_doc FOREIGN KEY (id_documents) REFERENCES DOCUMENTS (id_documents) ON DELETE CASCADE,
    CONSTRAINT fk_composer_prod FOREIGN KEY (id_produits) REFERENCES PRODUITS (id_produits) ON DELETE CASCADE
);
