name: Java CI with Maven (SteeveJobs)

on:
  push:
    branches: [ "main", "master", "develop", "hotfix/**" ]
  pull_request:
    branches: [ "main", "master", "develop", "hotfix/**" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build sur ${{ matrix.os_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os_name: Windows-x64
            jfx_classifier: win
            # Icône pour Windows (.ico)
            icon_path: src/main/resources/images/logo.ico

          - os: ubuntu-latest
            os_name: Linux-x64
            jfx_classifier: linux
            # Icône pour Linux (.png)
            icon_path: src/main/resources/images/logo.png

          - os: macos-latest
            os_name: macOS-Silicon-ARM64
            jfx_classifier: mac-aarch64
            # Icône pour Mac (.icns)
            icon_path: src/main/resources/images/logo.icns

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Compilation
        run: mvn -B clean compile "-Djfx.os=${{ matrix.jfx_classifier }}"

      - name: Tests Unitaires
        run: mvn -B test "-Djfx.os=${{ matrix.jfx_classifier }}"

      - name: Création de l'exécutable (Packaging)
        run: mvn -B package -DskipTests "-Djfx.os=${{ matrix.jfx_classifier }}" "-Dapp.icon=${{ matrix.icon_path }}"

      - name: Archivage de l'application (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: SteeveJobs-App-${{ matrix.os_name }}
          path: target/dist/